export enum SystemSettingKey {
  THERAPIST_BOOKING_ACCEPT_FEE = 'THERAPIST_BOOKING_ACCEPT_FEE',
  BOOKING_ACCEPT_TIMEOUT_MINUTES = 'BOOKING_ACCEPT_TIMEOUT_MINUTES',
  DEFAULT_SERVICE_RADIUS_KM = 'DEFAULT_SERVICE_RADIUS_KM',
}
